Include missing <time.h> header
Fixes the following compilation error on OS X with clang:

./ctags.h:9:2: error: unknown type name 'time_t'; did you mean 'size_t'?
        time_t mtime;
        ^~~~~~
        size_t

Signed-off-by: Gregory Petrosyan <gregory.petrosyan@gmail.com>